version: 2
updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      angular:
        patterns:
          - '@angular/*'
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major
  - package-ecosystem: nuget
    directories:
      - /src/ClashInsights.Api
      - /tests/ClashInsights.Tests
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      microsoft-ef:
        patterns:
          - 'Microsoft.AspNetCore.*'
          - 'Microsoft.EntityFrameworkCore*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
